parser: '@typescript-eslint/parser'
plugins:
  - import
  - jsx-a11y
  - prettier
  - react
  - react-hooks
  - '@typescript-eslint'
settings:
  import/resolver:
    babel-module:
extends:
  - eslint:recommended
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended
  - prettier
env:
  es2021: true
  node: true
  browser: true
globals:
  document: true
  window: true
rules:
  curly: off
  jsx-a11y/no-autofocus: off
  react/jsx-indent: off
  react/no-find-dom-node: off
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/indent': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unused-vars': ['warn']
