parser: '@typescript-eslint/parser'
plugins:
  - jsx-a11y
  - prettier
  - react
  - react-hooks
  - import
  - '@typescript-eslint'
settings:
  import/resolver:
    babel-module:
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - prettier
env:
  node: true
  browser: true
  es2021: true
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
  react/no-deprecated: warn
  import/no-extraneous-dependencies: error
  import/named: off
  import/namespace: off
  import/default: off
  react/jsx-indent: off
  jsx-a11y/mouse-events-have-key-events: warn
  jsx-a11y/no-autofocus: off
