semi: true
tabWidth: 2
trailingComma: all
singleQuote: true
printWidth: 120
overrides:
  - files: "*.yml"
    options:
      parser: yaml
      semi: false
  - files: ["*.tsx", "*.ts"]
    options:
      parser: typescript
      arrowParens: always