import React, { createContext } from 'react';
import { CellMeasurerCacheInterface } from 'react-virtualized/dist/es/CellMeasurer';
import { GridCellProps, GridDataProps } from './index.d';

type GridContextProps = {
  cache?: CellMeasurerCacheInterface;
  columnCount: number;
  columnKeyList: Array<string>;
  columnPropsList: Array<GridCellProps>;
  columnWidthList: Array<number>;
  data: Array<GridDataProps>;
  filterable: boolean;
  filterList: Array<string>;
  filteredData: Array<GridDataProps>;
  getColumnWidth: ({ index }: { index: number }) => void;
  getHeaderRowWidth: ({ index }: { index: number }) => void;
  getRowHeight: ({ index }: { index: number }) => void;
  getStickyColumnWidth: ({ index }: { index: number }) => void;
  getStickyRowWidth: ({ index }: { index: number }) => void;
  headerList: Array<Array<GridCellProps>>;
  headerKeyList: Array<Array<string>>;
  headerRowCount: number;
  height: number;
  isSortAsc?: boolean;
  onChange?: Function;
  onChangeFilterList?: (value: string, index: number) => void;
  overscanColumnCount?: number;
  overscanRowCount?: number;
  readOnly: boolean;
  rowCount: number;
  selectable?: boolean;
  setColumnWidthList: Function;
  setIsSortAsc: React.Dispatch<React.SetStateAction<boolean>>;
  setSortKey: React.Dispatch<React.SetStateAction<string>>;
  sortable?: boolean;
  sortKey?: string;
  stickyColumnCount: number;
  stickyColumnPropsList: Array<GridCellProps>;
  stickyHeaderList: Array<Array<GridCellProps>>;
  stickyHeaderKeyList: Array<Array<string>>;
  stickyHeaderRowCount: number;
  stickyColumnKeyList: Array<string>;
  stickyWidth?: number;
};

const GridContext = createContext({} as GridContextProps);
const GridProvider = GridContext.Provider;
const GridConsumer = GridContext.Consumer;

export default GridContext;
export { GridProvider, GridConsumer };
